AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for API Development

  Replace placeholders:
  - YourServiceName: Name of your service
  - YourFunctionName: Name of your Lambda function

# Global configuration for all Lambda functions
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: INFO
        POWERTOOLS_SERVICE_NAME: YourServiceName
        POWERTOOLS_METRICS_NAMESPACE: YourServiceName
    Tracing: Active  # Enable X-Ray tracing
    Tags:
      Environment: !Ref Environment
      Service: YourServiceName

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

  TableName:
    Type: String
    Default: YourServiceTable
    Description: DynamoDB table name

Resources:
  # ============================================================================
  # API Gateway
  # ============================================================================

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: NONE
        # Uncomment for API Key authentication
        # ApiKeyRequired: true
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogs.Arn
        Format: '$context.requestId $context.error.message $context.error.messageString'

  # ============================================================================
  # Lambda Functions
  # ============================================================================

  CreateResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-YourService-CreateResource
      CodeUri: src/
      Handler: handlers.create_resource.lambda_handler
      Description: Creates a new resource
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResourceTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /resources
            Method: POST

  GetResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-YourService-GetResource
      CodeUri: src/
      Handler: handlers.get_resource.lambda_handler
      Description: Retrieves a resource by ID
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ResourceTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /resources/{id}
            Method: GET

  ListResourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-YourService-ListResources
      CodeUri: src/
      Handler: handlers.list_resources.lambda_handler
      Description: Lists all resources with pagination
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ResourceTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /resources
            Method: GET

  UpdateResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-YourService-UpdateResource
      CodeUri: src/
      Handler: handlers.update_resource.lambda_handler
      Description: Updates an existing resource
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResourceTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /resources/{id}
            Method: PUT

  DeleteResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-YourService-DeleteResource
      CodeUri: src/
      Handler: handlers.delete_resource.lambda_handler
      Description: Deletes a resource
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResourceTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /resources/{id}
            Method: DELETE

  # ============================================================================
  # DynamoDB Table
  # ============================================================================

  ResourceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-${TableName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: YourServiceName

  # ============================================================================
  # CloudWatch Logs
  # ============================================================================

  ApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${Environment}-YourService
      RetentionInDays: 30

  # ============================================================================
  # CloudWatch Alarms
  # ============================================================================

  ApiErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-YourService-API-Errors
      AlarmDescription: Alert when API error rate is high
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiGateway

  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-YourService-Lambda-Errors
      AlarmDescription: Alert when Lambda error rate is high
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold

# ============================================================================
# Outputs
# ============================================================================

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${Environment}-YourService-ApiEndpoint

  ApiId:
    Description: API Gateway ID
    Value: !Ref ApiGateway
    Export:
      Name: !Sub ${Environment}-YourService-ApiId

  TableName:
    Description: DynamoDB table name
    Value: !Ref ResourceTable
    Export:
      Name: !Sub ${Environment}-YourService-TableName

  TableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt ResourceTable.Arn
    Export:
      Name: !Sub ${Environment}-YourService-TableArn
