openapi: 3.0.3
info:
  title: Todo API
  description: |
    A simple Todo API demonstrating spec-driven development with spec-kit.

    This API provides CRUD operations for managing todo items with filtering and pagination support.
  version: 1.0.0
  contact:
    name: Spec-Kit Example Team

servers:
  - url: http://localhost:8000
    description: Local development server

tags:
  - name: health
    description: Health check endpoints
  - name: todos
    description: Todo CRUD operations

paths:
  /health:
    get:
      summary: Health check
      description: Returns API health status
      tags:
        - health
      operationId: health_check
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: healthy

  /api/v1/todos:
    get:
      summary: List todos
      description: Retrieve a list of todos with optional filtering and pagination
      tags:
        - todos
      operationId: list_todos
      parameters:
        - name: completed
          in: query
          description: Filter by completion status
          required: false
          schema:
            type: boolean
        - name: priority
          in: query
          description: Filter by priority level
          required: false
          schema:
            type: string
            enum: [low, medium, high]
        - name: skip
          in: query
          description: Number of items to skip (pagination offset)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: limit
          in: query
          description: Maximum number of items to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
              example:
                - id: 550e8400-e29b-41d4-a716-446655440000
                  title: Buy groceries
                  description: Milk, eggs, bread
                  completed: false
                  priority: medium
                  created_at: '2026-01-18T10:00:00Z'
                  updated_at: '2026-01-18T10:00:00Z'
                - id: 550e8400-e29b-41d4-a716-446655440001
                  title: Finish report
                  description: null
                  completed: true
                  priority: high
                  created_at: '2026-01-18T09:00:00Z'
                  updated_at: '2026-01-18T11:00:00Z'

    post:
      summary: Create todo
      description: Create a new todo item
      tags:
        - todos
      operationId: create_todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
            example:
              title: Buy groceries
              description: Milk, eggs, bread
              priority: medium
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
              example:
                id: 550e8400-e29b-41d4-a716-446655440000
                title: Buy groceries
                description: Milk, eggs, bread
                completed: false
                priority: medium
                created_at: '2026-01-18T10:00:00Z'
                updated_at: '2026-01-18T10:00:00Z'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

  /api/v1/todos/{id}:
    get:
      summary: Get todo
      description: Retrieve a specific todo by ID
      tags:
        - todos
      operationId: get_todo
      parameters:
        - name: id
          in: path
          description: Todo ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Todo found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'

    put:
      summary: Update todo
      description: Update an existing todo (partial updates supported)
      tags:
        - todos
      operationId: update_todo
      parameters:
        - name: id
          in: path
          description: Todo ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
            example:
              completed: true
              priority: low
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

    delete:
      summary: Delete todo
      description: Delete a todo by ID
      tags:
        - todos
      operationId: delete_todo
      parameters:
        - name: id
          in: path
          description: Todo ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Todo deleted successfully
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: healthy

    Priority:
      type: string
      enum:
        - low
        - medium
        - high
      default: medium

    TodoBase:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Todo title (required)
        description:
          type: string
          maxLength: 1000
          nullable: true
          description: Todo description (optional)
        priority:
          $ref: '#/components/schemas/Priority'

    TodoCreate:
      allOf:
        - $ref: '#/components/schemas/TodoBase'

    TodoUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 1000
          nullable: true
        completed:
          type: boolean
        priority:
          $ref: '#/components/schemas/Priority'

    Todo:
      allOf:
        - $ref: '#/components/schemas/TodoBase'
        - type: object
          required:
            - id
            - completed
            - created_at
            - updated_at
          properties:
            id:
              type: string
              format: uuid
              description: Unique identifier
            completed:
              type: boolean
              default: false
              description: Completion status
            created_at:
              type: string
              format: date-time
              description: Creation timestamp
            updated_at:
              type: string
              format: date-time
              description: Last update timestamp

    ValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  anyOf:
                    - type: string
                    - type: integer
              msg:
                type: string
              type:
                type: string

    NotFoundError:
      type: object
      properties:
        detail:
          type: string
          example: Todo with ID 550e8400-e29b-41d4-a716-446655440000 not found
